spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devtoolbox?serverTimezone=UTC&characterEncoding=UTF-8
    username: devtoolbox
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  security:
    user:
      name: admin
      password: 1234

storage:
  upload-dir: uploads
  base-url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

logging:
  level:
    org.hibernate.SQL: warn

springdoc:
  swagger-ui:
    path: /swagger-ui.html
